### ISSUE TITLE
Is Result, Either and Reader implemented?

### ISSUE THREAD

**Issue by xileftenurb** [patrickmichalina/typescript-monads#65]
It is not clear in the README if the Result, Either and Reader monad are implemented or not.
is it the monad that is "To do" or only the documentation?

I found in the source some file for Either and Reader, but none for Result.

**Comment by patrickmichalina** [comment]
@xileftenurb good catch! Result is not implemented. The others have some implementations, but not extensive like a few other libraries. Feel free to submit PR's :)

**Comment by patrickmichalina** [comment]
I use Maybe and Reader the most. I would love to have some ability to map Readers together, but I think it would take something called a "Monad Transformer"

**Comment by xileftenurb** [comment]
Do you plan to implement Result soon?

**Comment by patrickmichalina** [comment]
If you need it, I should be able to within the next day. I will be needing it myself so its good motivation!

**Comment by patrickmichalina** [comment]
@xileftenurb I will improve the documentation in the next week or so. For now, result should be usable. Let me know if you find any issues. Cheers!
